### PR TITLE
Replace criterion with bpaf

### PR DESCRIPTION
**Pull request by pacak**
Might help with #1 :)

### CODE REVIEW

**Comment by pacak** [comment]
It's not yet compiling and parts are clearly missing. Feel free to take over or wait a bit for me to clean it up. :sleeping_bed:

**Comment by Boshen** [comment]
Oh wow I didn't want to bother you so I just left the issue there. How did you discover this?

clap is the only heavy dependency that I want to get rid of so badly :-)

**Comment by pacak** [comment]
> How did you discover this?

Every once in a while I do a ticket search, helps to find people having problems or cases like this.

Anyway. Pushed a new version, this one compiles and should, in theory, do everything correctly. Next logical step is to go over all the arguments it should be taking, make sure they work as expected. Maybe group things a bit.

**Comment by Boshen** [comment]
Remaining failure:

`Error: expected `--format=FORMAT`, got `--exact`. Pass `--help` for usage information`

And also a lint warning.

**Comment by Boshen** [comment]
One more 😅 

```
thread 'main' panicked at src/criterion.rs:453:30:
not yet implemented
```

**Comment by pacak** [comment]
> One more 😅

Yea, getting there. Currently going over all the options, cleaning up the output in `--help` and trying to structure them together a bit.

**Comment by Boshen** [comment]
Did you make a new release in order to support this PR ;-)

**Comment by pacak** [comment]
> Did you make a new release in order to support this PR ;-)

Just trying to get some stuff out that's been sitting done for a while. Looking at this PR as well, don't worry :)

**Comment by Boshen** [comment]
🤞 I want to remove `clap` from `oxc` so bad.

**Comment by Boshen** [comment]
```
thread 'main' panicked at /home/runner/work/criterion2.rs/criterion2.rs/src/analysis/mod.rs:49:13:
Baseline 'baseline' must exist before comparison is allowed; try --save-baseline baseline
```

**Comment by pacak** [comment]
> 🤞 I want to remove clap from oxc so bad.

Getting there :)

**Comment by pacak** [comment]
```
     Running `/home/runner/work/criterion2.rs/criterion2.rs/target/wasm32-wasi/release/deps/bench_main-871ca4172dd82c25.wasm --test --bench`
```

```
            .arg(Arg::new("test")
                .hide(true)
                .long("test")
                .num_args(0)
                .help("Run the benchmarks once, to verify that they execute successfully, but do not measure or report the results.")
                .conflicts_with_all(["list", "profile-time"]))
            .arg(Arg::new("bench")
                .hide(true)
                .long("bench")
                .num_args(0))
```

```
        let bench = matches.get_flag("bench");
        let test = matches.get_flag("test");
        let test_mode = match (bench, test) {
            (true, true) => true,   // cargo bench -- --test should run tests
            (true, false) => false, // cargo bench should run benchmarks
            (false, _) => true,     // cargo test --benches should run tests
        };
```

Passing both `--test` and `--bench` at the same time doesn't make much sense... You can either run benchmarks once or run them multiple times, not both. I imagine "test" meant to conflict with "bench" as well... Something-something, manual annotations, fragile.

I guess if we really want to maintain old behavior I can move `--test` into a standalone flag instead of operation and to the checks by hand?

**Comment by Boshen** [comment]
> ```
>      Running `/home/runner/work/criterion2.rs/criterion2.rs/target/wasm32-wasi/release/deps/bench_main-871ca4172dd82c25.wasm --test --bench`
> ```
> 
> ```
>             .arg(Arg::new("test")
>                 .hide(true)
>                 .long("test")
>                 .num_args(0)
>                 .help("Run the benchmarks once, to verify that they execute successfully, but do not measure or report the results.")
>                 .conflicts_with_all(["list", "profile-time"]))
>             .arg(Arg::new("bench")
>                 .hide(true)
>                 .long("bench")
>                 .num_args(0))
> ```
> 
>  ```
>         let bench = matches.get_flag("bench");
>         let test = matches.get_flag("test");
>         let test_mode = match (bench, test) {
>             (true, true) => true,   // cargo bench -- --test should run tests
>             (true, false) => false, // cargo bench should run benchmarks
>             (false, _) => true,     // cargo test --benches should run tests
>         };
> ```
> 
> Passing both `--test` and `--bench` at the same time doesn't make much sense... You can either run benchmarks once or run them multiple times, not both. I imagine "test" meant to conflict with "bench" as well... Something-something, manual annotations, fragile.
> 
> I guess if we really want to maintain old behavior I can move `--test` into a standalone flag instead of operation and to the checks by hand?

Shall we fix the test instead? The purpose of this fork is to fix stuff like this.

**Comment by pacak** [comment]
> Shall we fix the test instead? The purpose of this fork is to fix stuff like this.

I'm not sure where this test comes from, I suspect - from some external repo, at least `git grep test | grep bench` shows nothing.

**Comment by Boshen** [comment]
> > Shall we fix the test instead? The purpose of this fork is to fix stuff like this.
> 
> I'm not sure where this test comes from, I suspect - from some external repo, at least `git grep test | grep bench` shows nothing.

I think we just need to replicate this https://github.com/bheisler/criterion.rs/actions/runs/8510231188/job/23307389781#step:12:107

Which wants to run the thing in test mode.

It seems like `cargo wasi` accidentally passed in `--bench`, so perhaps we should just ignore it?

**Comment by Boshen** [comment]
:shipit:

**Pull request merged**
